KAFKA_SERVER = "localhost:9092"
RAW_TOPIC = "raw-text-files"
SANITIZED_TOPIC = "sanitized-data"
VALIDATED_TOPIC = "validated-data"
INPUT_DIR = "/home/dev1070/Downloads/Patient_data/"
INVALID_DIR = "Invalid_file"